server:
  port: 7001
  
config: 
  info: application

eureka:
  instance:
    #hostname: localhost 如果是单个，则不需要改本电脑中的hosts文件，否则，如下
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
    #设置eureka server 交互的地址查询服务和注册都需要依赖这个地址
      #配置方式一：
      #defualtZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群配置
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      #配置方式二：
      #这里配置方式一和配置方式二本质是相同的，只不过使用配置方式二需要在windows状态的hosts文件中做一个IP地址映射
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    #关闭自我保护模式，保证不可用服务被及时清除，默认是开启自我保护模式
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
